In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Define the function to calculate Basic Housing Space
def calculate_basic_housing_space(level):
    return (10 * np.sqrt(level**3) * 2) + 40

# Define a function to round down to the nearest even number
def round_down_to_nearest_even(number):
    rounded_number = np.floor(number)
    if rounded_number % 2 != 0:
        rounded_number -= 1
    return rounded_number

# Create a range of levels from 1 to 40
levels = np.arange(1, 67)

# Calculate the Basic Housing Space for each level
basic_housing_space = calculate_basic_housing_space(levels)

# Round down the results to the nearest even number
rounded_housing_space = np.vectorize(round_down_to_nearest_even)(basic_housing_space)

In [ ]:
# Plot the results
plt.figure(figsize=(12, 8))
plt.plot(levels, rounded_housing_space, marker='o', linestyle='-', color='b', label='Rounded Housing Space')
plt.xlabel('Level')
plt.ylabel('Basic Housing Space')
plt.title('Basic Housing Space by Level (Rounded Down to Nearest Even Number)')
plt.xticks(levels)
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
import pandas as pd

# Data provided with missing values in column 3 replaced with 0, and column 4 ignored
wine_data = [
    [1, 86, 0, 4, 12, 60],
    [2, 190, 0, 8, 24, 120],
    [3, 315, 0, 13, 36, 181],
    [4, 465, 80, 18, 48, 242],
    [5, 645, 104, 24, 61, 304],
    [6, 860, 135, 30, 73, 367],
    [7, 1119, 177, 37, 86, 430],
    [8, 1430, 229, 44, 99, 494],
    [9, 1803, 299, 51, 112, 559],
    [10, 2250, 388, 60, 125, 624],
    [11, 2787, 504, 68, 138, 691],
    [12, 3431, 657, 78, 152, 758],
    [13, 4203, 853, 88, 165, 826],
    [14, 5131, 1109, 99, 179, 896],
    [15, 6244, 1442, 110, 193, 966],
    [16, 7580, 1875, 122, 207, 1037],
    [17, 9183, 2438, 136, 222, 1109],
    [18, 11106, 3169, 150, 236, 1182],
    [19, 13414, 4120, 165, 251, 1256],
    [20, 16183, 5356, 180, 266, 1332],
    [21, 19507, 6963, 197, 282, 1408],
    [22, 23495, 9052, 216, 297, 1485],
    [23, 28281, 11768, 235, 313, 1564],
    [24, 34023, 15298, 255, 329, 1644],
    [25, 40915, 19887, 277, 345, 1725],
    [26, 49185, 25854, 300, 361, 1807],
    [27, 59108, 33610, 325, 378, 1891],
    [28, 71017, 43693, 351, 395, 1975],
    [29, 85306, 56801, 378, 412, 2061],
    [30, 102455, 73841, 408, 430, 2149],
    [31, 123032, 95994, 439, 448, 2238],
    [32, 147725, 124792, 472, 466, 2328],
    [33, 177357, 162230, 507, 484, 2419],
    [34, 212916, 210899, 544, 502, 2512],
    [35, 255585, 274168, 584, 521, 2606],
    [36, 306789, 356419, 626, 540, 2702],
    [37, 368233, 463345, 670, 560, 2800],
    [38, 441967, 602349, 717, 580, 2898],
    [39, 530448, 783054, 766, 600, 2999],
    [40, 636624, 1017969, 818, 620, 3101],
    [41, 764036, 1323361, 874, 641, 3204],
    [42, 916929, 1720368, 933, 662, 3310],
    [43, 1100402, 2236479, 995, 683, 3416],
    [44, 1320569, 2907424, 1060, 705, 3525],
    [45, 1584770, 3779650, 1129, 727, 3635],
    [46, 1901810, 4913547, 1203, 749, 3747],
    [47, 2282259, 6387610, 1280, 772, 3861],
    [48, 2738814, 8303891, 1361, 795, 3976],
    [49, 3286701, 10795057, 1449, 819, 4094],
    [50, 3944191, 14033573, 1541, 843, 4213],
    [51, 4733208, 18243642, 1640, 867, 4334],
    [52, 5680066, 23716732, 1745, 891, 4457],
    [53, 6816336, 30831747, 1857, 916, 4582],
    [54, 8179914, 40081266, 1976, 942, 4709],
    [55, 9816267, 52105638, 2102, 968, 4838],
    [56, 11779966, 67737320, 2237, 994, 4969],
    [57, 14136495, 88058503, 2380, 1021, 5103],
    [58, 16964436, 114476037, 2532, 1048, 5238],
    [59, 20358093, 148818827, 2694, 1075, 5375],
    [60, 24430637, 193464446, 2867, 1103, 5515],
    [61, 29317873, 251503743, 3050, 1131, 5657],
    [62, 35182779, 326954818, 3246, 1160, 5801],
    [63, 42220933, 425041200, 3453, 1189, 5947],
    [64, 50667036, 552553478, 3675, 1219, 6096],
    [65, 60802744, 718319416, 3910, 1249, 6247],
    [66, 72966054, 933815102, 4160, 1280, 6400],
    [67, 87562577, 1213959454, 4426, 1311, 6556],
    [68, 105079069, 1578147056, 4710, 1343, 6714],
    [69, 126099653, 2051590869, 5011, 1375, 6875],
    [70, 151325310, 2667067736, 5332, 1408, 7038]
]

# Convert the data to a NumPy array
wine_matrix = np.array(wine_data)

# Create a DataFrame for better readability
wine_df = pd.DataFrame(wine_matrix, columns=["Level", "Wood cost", "Marble cost", "Max Wine Served", "Basic Satisfaction Bonus", "Max Wine Bonus"])

# Display the DataFrame
print("Wine data matrix:")
print(wine_df)

In [ ]:
# New data provided, ignoring the 4th column
museum_data = [
    [1, 481, 240, 20, 50],
    [2, 1234, 1023, 41, 100],
    [3, 2363, 2212, 63, 150],
    [4, 4055, 4021, 88, 200],
    [5, 6595, 6769, 114, 250],
    [6, 10405, 10946, 144, 300],
    [7, 16119, 17296, 176, 350],
    [8, 24690, 26948, 211, 400],
    [9, 37548, 41618, 250, 450],
    [10, 56833, 63917, 294, 500],
    [11, 85762, 97812, 341, 550],
    [12, 129155, 149332, 395, 600],
    [13, 194244, 227642, 453, 650],
    [14, 291878, 346674, 518, 700],
    [15, 438329, 527603, 590, 750],
    [16, 658006, 802613, 670, 800],
    [17, 987521, 1220630, 759, 850],
    [18, 1481794, 1856015, 857, 900],
    [19, 2223204, 2821801, 965, 950],
    [20, 3335317, 4289796, 1086, 1000],
    [21, 5003487, 6521148, 1219, 1050],
    [22, 7505999, 9913144, 1367, 1100],
    [23, 11260150, 15069498, 1530, 1150],
    [24, 16891952, 22907948, 1711, 1200],
    [25, 25340520, 34823590, 1912, 1250],
    [26, 38014669, 52937193, 2134, 1300],
    [27, 57027835, 80472645, 2380, 1350],
    [28, 85550503, 122330751, 2652, 1400],
    [29, 128338880, 185961486, 2953, 1450],
    [30, 192528010, 282689952, 3286, 1500],
    [31, 288821553, 429732042, 3655, 1550],
    [32, 433276641, 653258546, 4064, 1600],
    [33, 649981434, 993053083, 4516, 1650],
    [34, 975071871, 1509592842, 5016, 1700],
    [35, 1462757402, 2294812419, 5569, 1750],
    [36, 2194360517, 3488466488, 6182, 1800]
]

# Convert the data to a NumPy array
museum_matrix = np.array(museum_data)

# Create a DataFrame for better readability
museum_df = pd.DataFrame(museum_matrix, columns=["Level", "Wood Costs", "Marble Costs", "Basic Satisfaction Bonus", "Max Culture Bonus"])

# Display the DataFrame
print("Museum data matrix:")
print(museum_df)