In [ ]:
import numpy as np

# Raw data as a list of lists
data = [
    [1, 4, 12, 60],
    [2, 8, 24, 120],
    [3, 13, 36, 181],
    [4, 18, 48, 242],
    [5, 24, 61, 304],
    [6, 30, 73, 367],
    [7, 37, 86, 430],
    [8, 44, 99, 494],
    [9, 51, 112, 559],
    [10, 60, 125, 624],
    [11, 68, 138, 691],
    [12, 78, 152, 758],
    [13, 88, 165, 826],
    [14, 99, 179, 896],
    [15, 110, 193, 966],
    [16, 122, 207, 1_037],
    [17, 136, 222, 1_109],
    [18, 150, 236, 1_182],
    [19, 165, 251, 1_256],
    [20, 180, 266, 1_332],
    [21, 197, 282, 1_408],
    [22, 216, 297, 1_485],
    [23, 235, 313, 1_564],
    [24, 255, 329, 1_644],
    [25, 277, 345, 1_725],
    [26, 300, 361, 1_807],
    [27, 325, 378, 1_891],
    [28, 351, 395, 1_975],
    [29, 378, 412, 2_061],
    [30, 408, 430, 2_149],
    [31, 439, 448, 2_238],
    [32, 472, 466, 2_328],
    [33, 507, 484, 2_419],
    [34, 544, 502, 2_512],
    [35, 584, 521, 2_606],
    [36, 626, 540, 2_702],
    [37, 670, 560, 2_800],
    [38, 717, 580, 2_898],
    [39, 766, 600, 2_999],
    [40, 818, 620, 3_101],
    [41, 874, 641, 3_204],
    [42, 933, 662, 3_310],
    [43, 995, 683, 3_416],
    [44, 1_060, 705, 3_525],
    [45, 1_129, 727, 3_635],
    [46, 1_203, 749, 3_747],
    [47, 1_280, 772, 3_861],
    [48, 1_361, 795, 3_976],
    [49, 1_449, 819, 4_094],
    [50, 1_541, 843, 4_213],
    [51, 1_640, 867, 4_334],
    [52, 1_745, 891, 4_457],
    [53, 1_857, 916, 4_582],
    [54, 1_976, 942, 4_709],
    [55, 2_102, 968, 4_838],
    [56, 2_237, 994, 4_969],
    [57, 2_380, 1_021, 5_103],
    [58, 2_532, 1_048, 5_238],
    [59, 2_694, 1_075, 5_375],
    [60, 2_867, 1_103, 5_515],
    [61, 3_050, 1_131, 5_657],
    # Add the remaining rows here if needed
]

# Converting the list of lists to a numpy array
array = np.array(data)

print(array)